CREATE TABLE COPY_EMP
AS SELECT * FROM EMPLOYEE ;

CREATE SEQUENCE SEQ_EMPID
START WITH 100
NOCACHE;

UPDATE COPY_EMP
SET EMP_ID = SEQ_EMPID.NEXTVAL;

ALTER TABLE COPY_EMP MODIFY ENT_YN CHAR(1) DEFAULT 'N';

COMMIT;

DROP TABLE PRODUCT;
DROP TABLE PRODUCT_IO;

CREATE TABLE PRODUCT(
    PRODUCT_ID VARCHAR2(20) PRIMARY KEY,
    P_NAME VARCHAR2(40) NOT NULL,
    PRICE NUMBER NOT NULL,
    DESCRIPTION VARCHAR2(100),
    STOCK NUMBER NOT NULL
);

INSERT INTO PRODUCT VALUES('nb_ss7', '삼성노트북', 1570000, '시리즈7', 0);
INSERT INTO PRODUCT VALUES('nb_ama4', '맥북에어', 1200000, 'xcode4', 0);
INSERT INTO PRODUCT VALUES('pc_ibm', 'ibmPC', 750000, 'window8', 0);

commit;

CREATE TABLE PRODUCT_IO(
    IO_NUM NUMBER PRIMARY KEY,
    PRODUCT_ID VARCHAR2(20) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE, 
    IO_DATE DATE DEFAULT SYSDATE NOT NULL,
    AMOUNT NUMBER NOT NULL,
    STATUS VARCHAR2(10) CHECK(STATUS IN('입고','출고'))
);

CREATE SEQUENCE SEQ_IO_NUM
NOCACHE;

CREATE OR REPLACE TRIGGER TRG_UPDATESTOCK
AFTER INSERT ON PRODUCT_IO
FOR EACH ROW
BEGIN
        IF :NEW.STATUS ='입고' THEN
            UPDATE PRODUCT
            SET STOCK = STOCK + :NEW.AMOUNT
            WHERE PRODUCT_ID = :NEW.PRODUCT_ID;
            
     ELSIF :NEW.STATUS ='출고' THEN
            UPDATE PRODUCT 
            SET STOCK = STOCK - :NEW.AMOUNT
            WHERE PRODUCT_ID = :NEW.PRODUCT_ID;
        END IF;  
END;
/

INSERT INTO PRODUCT_IO VALUES(SEQ_IO_NUM.NEXTVAL, 'nb_ss7', TO_DATE('19/07/01', 'RR/MM/DD'), 30, '입고');
INSERT INTO PRODUCT_IO VALUES(SEQ_IO_NUM.NEXTVAL, 'nb_ss7', TO_DATE('19/07/02', 'RR/MM/DD'), 5, '출고');
INSERT INTO PRODUCT_IO VALUES(SEQ_IO_NUM.NEXTVAL, 'pc_ibm', TO_DATE('19/07/02', 'RR/MM/DD'), 20, '입고');
COMMIT;
ROLLBACK;



    

