

CREATE TABLE COPY_EMP
AS SELECT * FROM EMPLOYEE ;

CREATE SEQUENCE SEQ_EMPID
START WITH 100
NOCACHE;

UPDATE COPY_EMP
SET EMP_ID = SEQ_EMPID.NEXTVAL;

ALTER TABLE COPY_EMP MODIFY ENT_YN CHAR(1) DEFAULT 'N';